name: Build Windows Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: "a42af01b72c28a8e1d7b48107b33e4f286a55ef6"

      - name: Install dependencies
        run: |
          vcpkg install libvips:x64-windows zlib:x64-windows

      - name: Configure CMake
        run: |
          cmake -B build -S . `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_TOOLCHAIN_FILE="${env:VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET=x64-windows

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Package
        run: |
          New-Item -ItemType Directory -Force -Path release
          Copy-Item build/Release/MyProject.exe release/
          Copy-Item README.md release/
          Copy-Item inputs.txt release/
          Copy-Item outputs.txt release/

          # Copy required DLLs from vcpkg
          $vcpkgBin = "$env:VCPKG_ROOT/installed/x64-windows/bin"
          Get-ChildItem "$vcpkgBin/*.dll" | Copy-Item -Destination release/

      - name: Create ZIP
        run: |
          Compress-Archive -Path release/* -DestinationPath MyProject-Windows-x64.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyProject-Windows-x64
          path: MyProject-Windows-x64.zip

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: MyProject-Windows-x64.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
