name: Build Windows Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download libvips
        run: |
          $vipsVersion = "8.15.2"
          $vipsUrl = "https://github.com/libvips/build-win64-mxe/releases/download/v$vipsVersion/vips-dev-w64-all-$vipsVersion.zip"
          Invoke-WebRequest -Uri $vipsUrl -OutFile vips.zip
          Expand-Archive -Path vips.zip -DestinationPath .
          Move-Item vips-dev-8.15 C:\vips

      - name: Setup environment
        run: |
          echo "C:\vips\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Configure CMake
        run: |
          cmake -B build -S . `
            -DCMAKE_BUILD_TYPE=Release `
            -DVIPS_INCLUDE_DIR=C:/vips/include `
            -DVIPS_LIBRARY_DIR=C:/vips/lib `
            -DZLIB_INCLUDE_DIR=C:/vips/include `
            -DZLIB_LIBRARY=C:/vips/lib/libz.dll.a

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Package
        run: |
          New-Item -ItemType Directory -Force -Path release
          Copy-Item build/Release/MyProject.exe release/
          Copy-Item README.md release/
          Copy-Item inputs.txt release/
          Copy-Item outputs.txt release/

          # Copy required DLLs
          Copy-Item C:\vips\bin\*.dll release\

      - name: Create ZIP
        run: |
          Compress-Archive -Path release\* -DestinationPath MyProject-Windows-x64.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyProject-Windows-x64
          path: MyProject-Windows-x64.zip

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: MyProject-Windows-x64.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
